### ISSUE TITLE
Apply to only selected records

### ISSUE THREAD

**Issue by marcelgrosskopff** [leanpanda-com/datocms-plugins#1]
Is there any possible way to apply the properties to only selected records?

**Comment by joeyates** [comment]
Hi @marcelgrosskopff as this repo contains a collection of plugins, could you specify which plugin you are intending?

**Comment by marcelgrosskopff** [comment]
Hi, sorry - I meant the Bulk-Editor
If thats not possible a workaround would be to set a switch in the global permission that the bulk edit only edits unpublished items. In that way you can filter, select and unpublish the desired records!

**Comment by joeyates** [comment]
That's a good idea, and we'd welcome a PR, but, at present, there's no intention to implement that ourselves.
